config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts
  resources :users, only: [:show], param: :username, path: ''

  root to: 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :image, attached: true

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, uniqueness: true, presence: true

  has_one_attached :avatar

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[avatar available name username bio])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to posts_path, notice: "Created Post"
    else
      render :new, notice: "Please try again"
    end
  end

  private

  def post_params
    params.require(:post).permit(:image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by!(username: params[:username])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
    success: 'alert-success',
    error: 'alert-danger',
    alert: 'alert-warning',
    notice:'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def avatar_url_for(user, options={})
    size = options[:size] || 32

    if user.avatar.attached?
      user.avatar.variant(
        resize: "#{size}x#{size}!"
      )
    else
      hash = Digest::MD5.hexdigest(user.email.downcase)
      "https://secure.gravatar.com/avatar/#{hash}.png?s=#{size}"
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flash/app'%>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local:true) do |f| %>
<% if f.object.errors.any?%>
<p>
<%= pluralize(f.object.errors.count, "error") %> prevented the form from being saved:
</p>

<ul>
  <% f.object.errors.full_messages.each do |message|%>
    <li>
      <%= message %>
    </li>
  <%end%>
</ul>
<% end %>
  <%= f.hidden_field :post, value: f.object%>
  <div class="form-group">
    <%= f.label :image, "Your Image" %>
      <div class="custom-file">
        <%= f.file_field :image, class: "custom-file-input"  %>
        <label class="custom-file-label">
          select file...
        </label>
      </div>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%=image_tag post %>
<% end %>

app/views/posts/new.html.erb
<div class="container">
  <div class = 'justify-content-center align-items-center'>
    <div class= 'row'>
      <div class='col-md-8 col-lg-8 mx-auto my-5'>
        <div class= 'card shadow-sm'>
          <div class='card-body p-5'>
            <h2 class= 'my-3'>Share Something</h2>
            <hr/>
            <%= render "form", post:@post %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <div class= 'container'>
  <%= link_to "Railsgram", root_path , class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">

      <ul class="navbar-nav">
        <%= link_to 'Explore', root_path, class: 'nav-link' %>
      </ul>
      <ul class="navbar-nav ml-auto">
      <% if user_signed_in?  %>
        <li class="nav-item">
          <%= link_to 'Upload', new_post_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to  user_path(current_user.username), class: 'nav-link' do %>
            <%= image_tag avatar_url_for(current_user, size:24), class: 'rounded-circle mr-1' %>
            <%= current_user.username %>
          <%end%>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/flash/_app.html.erb
<% flash.each do |key,value|%>
  <div class="alert <%= bootstrap_class_for(key)%> alert-dismisable">
  <div class="contiainer">
  <%= value %>
  <button type="button" class="close" data-dismiss="alert">
    <span class="pointerless" aria-hidden="true">&times;</span>
  </button>
  </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="d-flex align-items-center justify-content-center mt-5">
  <div class= "media mr-5 align-self-start">
    <%= image_tag avatar_url_for(@user, size:128), class: 'rounded-circle ml-4' %>
  </div>
  <div class="media">
    <div class = "media-body">
      <div class = "d-flex flex-row align-items-center justify-content-between">
        <h1><%= @user.username%></h1>
        <%= link_to "Edit", edit_user_registration_path, class: "ml-3 btn btn-secondary btn-sm" if current_user.id ==@user.id %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>